### ISSUE TITLE
guppy pre-commit fresh install breaks the build

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [therealklanni/guppy-pre-commit#6]
If I create fresh dir (like team city does) and try to install package guppy post action hangs

mkdir tmp
cd tmp
npm i guppy-pre-commit

this is critical for us because our CI stops.
this happens because there is no git folder yet.

Can you solve this asap?

**Comment by therealklanni** [comment]
See [my response to your other issue](https://github.com/therealklanni/git-guppy/issues/82#issuecomment-232505073).
