### ISSUE TITLE
guppy-pre-commit 0.3.0 doesn't use guppy-cli 1.0.1

### ISSUE THREAD

**Issue by 1nd** [therealklanni/guppy-pre-commit#7]
How to reproduce:
Run `npm install guppy-pre-commit`.

Expected:
Get `guppy-pre-commit` 0.3.0 and `guppy-cli` 1.0.1.

Actual:
Get `guppy-pre-commit` 0.3.0 and `guppy-cli` **0.4.0**.

**Comment by therealklanni** [comment]
Thanks, I will get to this as soon as I can.

**Comment by therealklanni** [comment]
Published v0.4.0 with guppy-cli 1.0.1
