### ISSUE TITLE
`sh: guppy: command not found` thrown by postinstall

### ISSUE THREAD

**Issue by klokie** [therealklanni/guppy-pre-commit#9]
I'm seeing the following error triggered when installing a dependency that uses `guppy-pre-commit`:

```
   sh: guppy: command not found
   npm ERR! file sh
   npm ERR! code ELIFECYCLE
   npm ERR! errno ENOENT
   npm ERR! syscall spawn
   npm ERR! guppy-pre-commit@0.3.0 postinstall: `guppy pre-commit`
   npm ERR! spawn ENOENT
```

It's not clear to me how the postinstall step is supposed to find a binary called `guppy`, but when I replace that `guppy pre-commit` command with `/usr/bin/true` or `echo OK` then the installation completes without error. 
I'm on a Mac, but wondering if maybe this could be related to #2 ?

**Comment by therealklanni** [comment]
Thanks for the report. guppy-pre-commit should install `guppy-cli` as a dependency, that's where the `guppy` command is provided.

Could you post your node/npm versions, also what dependency uses guppy-pre-commit (along with its version) and any other information that might be relevant?

Also, this doesn't appear to be related to issue 2.

**Comment by klokie** [comment]
Thanks for the reply!
My project has `git-guppy` version 2.1.0 as a devDependency
which depends on `guppy-pre-commit` version 0.3.0 as a devDependency
which depends on `guppy-cli` version 1.0.1 as a dependency

However, `guppy-cli` is not installed globally so it cannot simply be found when running `guppy`, can it?

```
$ npm -v
4.1.2
$ node -v
v7.7.4
$ which -s guppy || echo not found
not found
```

**Comment by therealklanni** [comment]
It should be using the bin installed by npm in the local `node_modules` dir. 

Would you mind creating a repo that has a minimal project that reproduces the issue you're having? I will check it out and see if I can determine what's going wrong. Thanks!

**Comment by klokie** [comment]
I tried to create a simple repo to test the `pre-commit` functionality but for some reason the hook just wouldn't install.
Anyway, I was able to get around the issue by adding `guppy-cli` as a `devDependency`. 
Thanks for your help.

**Comment by therealklanni** [comment]
I'll go ahead and leave this open in case anyone else runs into the same issue and can provide more information to help me understand what's going wrong. Thanks.

**Comment by ohsevin** [comment]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.9.4-galliumos-braswell
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! guppy-pre-commit@0.4.0 postinstall: `guppy pre-commit`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the guppy-pre-commit@0.4.0 postinstall script 'guppy pre-commit'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the guppy-pre-commit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     guppy pre-commit
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs guppy-pre-commit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls guppy-pre-commit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/artik/Downloads/popcorn-desktop/npm-debug.log
Local dependencies encountered an error while installing

**Comment by nhovratov** [comment]
This has to be some kind of PATH error. I had the same issue, then I tried installing npm packages in another directory and it worked.
Somehow the PATH variable `/c/my-path/my-project/node_modules/.bin` was not set. Setting it manually with `export "$PATH:/c/my-path/my-project/node_modules/.bin"` solved the problem.

**Comment by therealklanni** [comment]
Thanks for sharing @nhovratov 👍
